name: Deploy ðŸ˜Ž

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types:
      - published


env:  
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  test:
    name: Test project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository ðŸ‘€
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: time-arena-game/Library
          key: Library-time-arena
      
      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        with:
          projectPath: time-arena-game
          githubToken: ${{ secrets.GITHUB_TOKEN }} 

  build:
    if: github.event.action == 'published'
    name: Build my project âœ¨
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      # Checkout
      - name: Checkout repository ðŸ‘€
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: time-arena-game/Library
          key: Library-time-arena
          restore-keys: Library-

      # Build
      - name: Build project ðŸ”¨
        uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          projectpath: time-arena-game
          targetPlatform: WebGL

      # Deploy
      - uses: josephbmanley/butler-publish-itchio-action@master
        if: github.event.action == 'published'
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: webgl
          ITCH_GAME: time-arena
          ITCH_USER: eldonelectronic
          PACKAGE: build/WebGL/WebGL

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build

