name: Deploy ðŸ˜Ž

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:  
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  test:
    name: Test project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository ðŸ‘€
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: time-arena-game/Library
          key: Time-Arena-Library
      
      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        with:
          projectPath: time-arena-game
          githubToken: ${{ secrets.GITHUB_TOKEN }} 

  build:
    name: Build my project âœ¨
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      # Checkout
      - name: Checkout repository ðŸ‘€
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: time-arena-game/Library
          key: Library-time-arena
          restore-keys: Library-

      # Build
      - name: Build project ðŸ”¨
        uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          projectpath: time-arena-game
          targetPlatform: WebGL


    # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build

      # - name: Deploy ðŸš€
      #   uses: JamesIves/github-pages-deploy-action@v4.2.3
      #   with:
      #     branch: deploy # The branch the action should deploy to.
      #     folder: build/WebGL/WebGL # The folder the action should deploy.

#       - id: 'auth'
#         uses: 'google-github-actions/auth@v0'
#         with:
#           credentials_json: '${{ secrets.gcp_credentials }}'

#       - id: 'upload-files'
#         uses: 'google-github-actions/upload-cloud-storage@v0'
#         with:
#           path: 'build'
#           destination: 'eldonelectronic.co.uk'
#           #parent: false
